name: CICD Pipeline - Stage Env
on:
  pull_request:
    types: [closed]
    branches:
      - stage
  push:

env:
  APP_NAME: ci-cd-test


jobs:
#  test:
#    if: ${{github.event}} == 'push'
#    runs-on: ubuntu-20.04
#    steps:
#      - name: UnitTests
#        run: echo "this is a test"


  build:
    if: ${{github.event}} == 'push'  # 'pull_request'
#    needs: [test]
    runs-on: ubuntu-20.04
    container: amazon/aws-cli
    services:
      docker:
        image: docker:dind
    environment: stage
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      DOCKER_REGISTRY_URL: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com
      COMMIT_HASH: ${{ github.sha }}
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v2.3.4
      - name: Docker Build and Push
        run: |
          amazon-linux-extras install docker
          aws --version
          docker --version
          aws ecr get-login-password | docker login --username AWS --password-stdin $DOCKER_REGISTRY_URL
          docker build --pull -t "$DOCKER_REGISTRY_URL/$APP_NAME:$COMMIT_HASH" .
          docker push "$DOCKER_REGISTRY_URL/$APP_NAME:$COMMIT_HASH"


#
#  tf-run:
#    if: contains( github.ref, 'stage') && github.event == 'pull-request' # needs to fix
#    needs: [test, docker-build]
#    runs-on: